# STACK TWO

Resources:

  RobotAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      VpcId: !Ref DefaultVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  RobotAppServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.large
      ImageId: ami-087c17d1fe0178315
      SecurityGroupIds:
        - !Ref RobotAppSecurityGroup

  RobotS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
