# STACK TWO

AWSTemplateFormatVersion: '2010-09-09'
Description: Multi-region safe EC2 + Security Group + S3 stack

Parameters:
  DefaultVPC:
    Type: AWS::EC2::VPC::Id
    Description: Select the default VPC for the region

Resources:

  RobotAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      VpcId: !Ref DefaultVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  RobotAppServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      ImageId: 
        !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}"
      SecurityGroupIds:
        - !Ref RobotAppSecurityGroup
      Tags:
        - Key: Project
          Value: RobotApp

  RobotS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
